@startuml
' Título do Diagrama
title Diagrama de Casos de Uso - Sistema de Gestão Escolar

' Layout da esquerda para a direita
left to right direction

' Definição dos Atores
actor Model.Administrador
actor Model.Professor
actor Model.Aluno

' Delimitação do Sistema com um retângulo
rectangle "Sistema de Gestão Escolar" {
  ' Casos de Uso do Model.Administrador
  (Cadastrar Model.Aluno) as UC1
  (Cadastrar Model.Professor) as UC2
  (Criar Disciplina) as UC3
  (Matricular Model.Aluno em Disciplina) as UC4

  ' Caso de Uso do Model.Professor
  (Lançar Notas e Faltas) as UC5

  ' Caso de Uso Compartilhado
  (Consultar Alunos da Disciplina) as UC6
  (Consultar Notas e Faltas) as UC7
  (Consultar disciplinas) as UC8
}

' Relacionamentos do Model.Administrador com os Casos de Uso
Model.Administrador --> UC1
Model.Administrador --> UC2
Model.Administrador --> UC3
Model.Administrador --> UC4

' Relacionamento do Model.Professor com os Casos de Uso
Model.Professor --> UC5

' Ambos os atores podem realizar a consulta
Model.Administrador --> UC6
Model.Professor --> UC6

' Todos os atores podem realizar a consulta
Model.Administrador --> UC7
Model.Professor --> UC7
UC7 <-- Model.Aluno

' Ambos os atores podem realizar a consulta
Model.Professor --> UC8
UC8 <-- Model.Aluno
@enduml