@startuml

' Título do Diagrama
title Diagrama de Casos de Uso - Sistema de Gestão Escolar

' Layout da esquerda para a direita
left to right direction

' Definição dos Atores
actor Administrador
actor Professor
actor Aluno

' Delimitação do Sistema
frame "Sistema de Gestão Escolar" {

usecase "Cadastrar Aluno" as UC1
usecase "Cadastrar Professor" as UC2
usecase "Criar Disciplina" as UC3
usecase "Matricular Aluno em Disciplina" as UC4
usecase "Alocar Professor em Disciplina" as UC5
usecase "Consultar Alunos" as UC6
usecase "Consultar Notas" as UC7
usecase "Consultar Faltas" as UC8
usecase "Lançar Nota" as UC9
usecase "Lançar Falta" as UC10
usecase "Consultar Disciplinas" as UC11
}

' Relacionamentos do Administrador com os Casos de Uso
Administrador --> UC1
Administrador --> UC2
Administrador --> UC3
Administrador --> UC4
Administrador --> UC5

' Relacionamento do Professor com os Casos de Uso
Professor --> UC9
Professor --> UC10

' Ambos os atores podem realizar a consulta
Administrador --> UC6
Professor --> UC6

' Todos os atores podem realizar a consulta
Administrador --> UC7
Professor --> UC7
UC7 <-- Aluno
Administrador --> UC8
Professor --> UC8
UC8 <-- Aluno
Administrador --> UC11
Professor --> UC11
UC11 <-- Aluno

@enduml
